# Generated by Django 3.0.5 on 2021-02-19 20:59

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('headline', models.TextField()),
                ('article_link', models.TextField()),
                ('date', models.TextField()),
                ('source_site', models.TextField()),
                ('created_at', models.TextField()),
            ],
        ),
    ]
